local Services = {}

local _FullProfileStructure = {}

function Services:GetService(_ServiceName)
	-- will return the Service called "ServiceName" required
end

function Services:InitializeAllServices()
	-- will define each Service its Config Module and its ReactionEvent
	-- will init every Service Module
	-- will add more elements to the FullProfileStructure from each Service to make players get the required structure when they join
end

return Services
